version: "3.8"
services:

  php:
    image: docker.pkg.github.com/magicloud/images/php-fpm:224922f
    networks:
      - virtualbox
    volumes:
      - "/mnt/data/phpvirtualbox:/app"

  phpvbox:
    image: docker.pkg.github.com/magicloud/images/php-frontend:224922f
    command: php:9000 80
    networks:
      - virtualbox
    volumes:
      - "/mnt/data/phpvirtualbox:/app"

networks:
  virtualbox:
