version: "3.8"
services:

  aria2:
    image: docker.pkg.github.com/magicloud/images/aria2:f87b3eb
    networks:
      - download
    volumes:
      - "downloads:/downloads:rw"

  aria2.proxy:
    image: docker.pkg.github.com/magicloud/images/reverse-proxy:f963a97
    command: 6800 http://aria2:6800 'Access-Control-Allow-Origin:*'
    networks:
      - download

  ariang:
    depends_on:
      - aria2
    image: docker.pkg.github.com/magicloud/images/ariang:1234ae0
    command: http/aria2/6800/jsonrpc
    networks:
      - download

networks:
  download:

volumes:
  downloads:
    external: true
